npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: 1870519A-0519-43D1-B2DD-63477423FC88

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: 1870519A-0519-43D1-B2DD-63477423FC88